### ISSUE TITLE
Allow coordinators to add project proposals

### ISSUE THREAD

**Issue by srish** [sagesharp/outreachy-django-wagtail#102]
If I figured the existing workflow right, then currently only mentors can add project proposals to their community's page. And, coordinators can only approve the projects but do not have the permissions right now to add them. 

It would be useful to allow coordinators to add project proposals and that way have one less admin work for mentors! :)

**Comment by sagesharp** [comment]
Unfortunately, it was a design constraint that mentors be the only ones to submit their own projects, and I don't want to allow coordinators to submit projects. There's a couple reasons for this:

1. In the past we've had mentors get overwhelmed from working with many applicants, only to have it turn out that many of them weren't eligible for the program. The new Outreachy website eliminates that, by hiding project and community details from people who haven't submitted an eligible check (or submitted one and they aren't eligible). 

Eligible Outreachy applicants will be encouraged to track their contributions by entering them on the project listing on the website, and once they submit one contribution, they'll be able to submit their final application. Forcing applicants to list a contribution before they can complete their application means less work for mentors and coordinators to wade through applications that aren't eligible because the applicant didn't make a contribution.

This also gives Outreachy mentors a dashboard view into the applicants who have submitted contributions. They can encourage ones that haven't tracked it to submit them. Only applicants who have done an eligibility check can submit a contribution to the project. This allows Outreachy mentors to check if a person they're working with is actually eligible for Outreachy.

In short, mentors will find that the Outreachy website is much more useful to them than just for listing their project. They need to be able to have direct access to their project in order to see which eligible applicants are listing their contributions.

2. The new Outreachy application system will be directly tied into the projects that the mentors submit on the website. Outreachy mentors will be able to select their interns from the applicants who submitted their contributions to that project on the website. Only the mentor who submitted the project (or a co-mentor) will be able to select an intern. Why? Because we've had coordinators in the past pick an intern for a mentor before, only to have that mentor back out of the time commitment. That left the coordinator in the awkward position of mentoring two Outreachy interns until they could find additional mentors.

3. Mentors need to fill out very detailed information about their project (repositories, newcomer tags in issue trackers, communication channels, etc), their contact information, their mentorship style, and how to make the first contributions to their project. Mentors also make the decision about whether they want to share their pronouns with the Outreachy applicants on the project page, and that's not a decision a coordinator can make for them.

4. When a mentor submits their project and it is approved by the coordinators, their email address is added to an internal list that the Outreachy organizers use to periodically subscribe mentors to the Outreachy mentors mailing list. This saves Outreachy organizers a ton of time, as we've often spent hours in the past tracking down mentors on IRC just because they don't have an email listed on their community's landing page.

5. (This is the most important reason.) During the past Outreachy rounds, there is always a scramble to on-board mentors in the Outreachy application system at the last minute. This involves a massive amount of work on the Outreachy organizer's part, during a period when we need to be spending our time seeking additional funding. Therefore, we need to onboard mentors as soon as possible. Given that some of our mentors are especially adverse to "paperwork", the best time to incentivize them to sign up is in order to get their project listed.

**Comment by srish** [comment]
Thank you for the helpful explanation! It is now super clear to me, and I appreciate this design decision :)

**Comment by sagesharp** [comment]
Thanks for understanding!

**Comment by JuliaLawall** [comment]
Could it be a compromise to allow the coordinator to edit the proposals?
