### ISSUE TITLE
Add online classes/coding school time commitments

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#135]
We've already had a couple people get rejected because they made up the number of credit hours for a coding school or online class.

**Comment by sagesharp** [comment]
Apologies to the applicants that have had to resubmit their application forms because we didn't collect this information in the first place!

**Comment by KoniKodes** [comment]
A friend of mine is in the freeCodeCamp women's chat room, where I first heard about Outreachy.

She's currently attending a self-paced evening program with FlatIron - which is similar to freeCodeCamp in the curriculum. She's been denied because of this. 

Is there a way to have her access the same eligibility page that I did?

She is strong in Java, and active on the freeCodeCamp forums. I strongly believe that she would be a great Outreachy Intern.

**Comment by KoniKodes** [comment]
Correction: She said to me that "I am in school that is a recognized diploma program. It's blended so I'm only in class 3 times a week for 3 hrs each of those days. The rest is done from home."
