### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by up776060** [sagesharp/outreachy-django-wagtail#157]
Just a small Typo spotted whilst looking at fixing the Typo in eligibility form, but struggling to get the code base running on my machine.

Typo is located under **Setting Up Your Development Environment** and is a small spelling mistake of Python, which reads Pyton.

**Comment by sagesharp** [comment]
Thanks for reporting this, @up776060! In the future, when you make your git commit (with `git commit -v` instead of `git commit -m`, you can add a blank line and then a line that says `Fixes #157`. When you do that, github will automatically close the issue when the pull request is merged.

Good luck in your future open source development!
