### ISSUE TITLE
Add Django debug toolbar & template debugging

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#210]
This issue basically serves to document my confusion with getting tools to debug issues I'm having with templates. I've been hitting a wall debugging templates, where I've been tinkering, but I need more insight into the variables in the templates and what they are.

The tools I've found so far are django-debug-toolbar and (possibly related??) django-template-debug. Django debug toolbar has some sort of template debugging, but I'm not sure how to use it, since the documentation provides no usage examples and doesn't link to any documentation about the base. The Django template debug package documentation does provide usage examples, so while I've installed the toolbar, I don't know if that's necessary??

(Oh, wait, the Django template debug package documentation link to usage examples is broken?? [That's a really disheartening ASCII art to display](https://django-template-debug.readthedocs.io/en/latest/_templates/quick_start.html#example-usage))

I want to ensure that debug tools aren't available on the production website. The Django debug toolbar seems to have me adding apps and middleware directly to outreachyhome/settings/base.py, which concerns me. I think it won't be an issue because the code will be turned off if DEBUG isn't set to True, but it makes me nervous. The Djanog template debug package has its own variable, TEMPLATE_DEBUG, which is only set to true in outreachyhome/settings/dev.py, so that reassures me more. Still, I have no idea what I'm doing here, so it's time to get some advice.

I'm unsure whether I need to commit requirements.txt with the debug toolbar and template debugging requirements. Is it safe to have those if debugging is turned off in production? Should I only be adding the apps and middleware in outreachyhome/settings/dev.py instead of outreachyhome/setting/base.py?

I'm also unsure if I've added debug_toolbar.middleware.DebugToolbarMiddleware in the right place in the MIDDLEWARE list. The documentation says it needs to be as early as possible, but not before any middleware that "encodes the response's content". I assume they mean the HTTP response content?? The documentation assumes I have background in HTTP request/response processes, and I don't. :crying_cat_face:

I've guessed that it should come after XForwardedForMiddleware, since XForwarding is associated with the HTTP response. I'm guessing it might need to come after 'django.middleware.security.SecurityMiddleware', since that might deal with HTTPS responses, but I'm unsure if it needs to come after 'whitenoise.middleware.WhiteNoiseMiddleware' I'm unsure if the list was even put together by ensuring the response content middleware should come first. Again, time to consult a mentor.

**Comment by jameysharp** [comment]
These are good questions. :smile:

I hadn't seen django-template-debug before, but yeah, the documentation is sparse and it's had three commits in as many years, so I'm kind of skeptical of it.

With django-debug-toolbar installed, you shouldn't need to change any code or templates: just load your local dev site in a browser, open the new toolbar that appears on the side, and you should have a "Templates" tab to explore there. Exploring the other tabs should give you a good idea of what else the debug toolbar can do for you. I think they didn't bother documenting the individual tabs because the way to use them is pretty easily discoverable if you know how to get to the toolbar in the first place.

I trust django-debug-toolbar to no-op when `DEBUG` is `False`, but if you want to be absolutely sure, we can do more complicated things to only insert it in the relevant lists when using `settings/dev.py`. Either way, though, you should add it to `requirements.txt` so other people running local dev copies get it installed correctly too. There are ways to separate the dependencies for dev from the dependencies for production though; I've opened a new issue, #211, about that.

It isn't easy to check, but I'm pretty sure none of the middleware currently in `settings/base.py` modify the encoding of the response body. (What they mean by that is they look inside the Response object to find the HTML you're returning so they can insert some extra stuff just before the `</body>` tag at the end, but if the response has been gzipped for example then they can't read it to do that.)

I believe if you insert the debug toolbar as the first middleware, you'll be able to tell that I guessed wrong if you just don't see the toolbar appear. In that case you could place it last and make sure it at least shows up then; if so, then you can binary-search to find the right place to put it in the list. This seems like it would be useful advice for the upstream documentation, assuming I'm correct about it...

I hope this helps!

**Comment by sagesharp** [comment]
To document what finally solved my problem: I could see that the Django debug toolbar was loaded, however, clicking elements did nothing. It turned out that my JavaScript blocker was stopping it from working. Even after I whitelisted some sites, it seems to need JavaScript enabled for the entire tab.

If you have issues with Django debug toolbar, check to see if you're running the NoScript plugin, and disable it for your tab!
