### ISSUE TITLE
Blog index page

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#217]
Please add a link to the blog under the new 'About Us' menu.

**Comment by jameysharp** [comment]
I've pushed a new Wagtail model, `BlogIndex`, which you'll need to replace the current /blog/ with. I have not linked it from the navbar because I think you should glance over it, and update the live site to use the new page type, before linking people to it.

I don't think there's currently a good way to extract a summary of each blog post to display on the index page, because those posts are allowed to be any type of page. In particular the only post right now is of type `StatsRoundFifteen`, which has no information in the page object itself; everything's hidden away in the template. So for now the index page only shows page title, publication date, and authorship info. We can work on this later unless you think summaries are critical.

You may want to review the index template and see if you want it formatted differently.

I haven't implemented RSS or Atom feeds yet, because I can work on that while you're reviewing the above bits. However, feed readers that support the [microformats2 h-feed specification](http://microformats.org/wiki/h-feed) can get the feed info directly from the index page right now.

**Comment by jameysharp** [comment]
I've now also pushed support for generating Atom feeds, as well as the feed auto-discovery tag so people can just pass the `https://outreachy.org/blog/` URL to a feed reader and it can find the Atom feed automatically.

It might be a good idea to also grab an RSS icon ("The Mozilla Foundation has made these icons freely available for use by others": http://www.feedicons.com/) and link the feed from somewhere on the page that's visible to humans.

**Comment by sagesharp** [comment]
The code is live, thanks @jameysharp!
