### ISSUE TITLE
Need a date picker for time commitments date

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#244]
There are so many people who aren't able to put dates into YYYY-MM-DD format. :( @jameysharp can explain where he's stuck.

**Comment by jameysharp** [comment]
We can get a long way by just ensuring that the widgets for these fields have a `type="date"` attribute instead of `type="text"`. On older browsers both types render the same way, but newer browsers provide date-picking UI.

Django documentation says this can be done by constructing the `DateInput` widget with an `attrs={ 'type': 'date' }` argument. (https://docs.djangoproject.com/en/1.11/ref/forms/widgets/#styling-widget-instances)

Conveniently, you're already overriding many of the widgets in forms in the `EligibilityUpdateView` class, so there are lots of examples of how to do this.

Once that's in place, we can optionally add JavaScript polyfills that provide better UI for the older browsers as well, but according to <https://caniuse.com/#feat=input-datetime> there's already `type="date"` support in over 86% of browsers worldwide, so I'm not too worried about it.

For what it's worth, apparently Django decided 7 years ago to not do this by default, because it could do bad things if localization is turned on. Fortunately we haven't implemented localization yet. :disappointed_relieved: See https://code.djangoproject.com/ticket/16630#comment:11

**Comment by jameysharp** [comment]
I think we fixed this in 154a46badd42b08fe6043ea0befa85211f0d9774
