### ISSUE TITLE
Send email to mentor when project is accepted for an approved community

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#54]
When a Project is approved by a FOSS community coordinator for an approved community, we need to let mentors know what actions to take next.

To: newly approved mentors in an approved community
- Subject: Project approved to participate in Outreachy
- action -> create gmail filter for mentors mailing list RIGHT NOW
- (?) action -> if approved projects with mentors, link to community landing page, they can start advertising their community

For each approved mentor in an approved community:
- To: subscribe email address for mentors mailing list
- Subject: subscribe

**Comment by jameysharp** [comment]
As far as I can tell, this is done. We decided not to wait for the community to be approved before telling the mentor that their project is approved, because they can usefully update it while waiting for community participation questions to get sorted out, and because we're no longer tying mailing list subscription to the same notification.
