### ISSUE TITLE
Organize menu items

### ISSUE THREAD

**Issue by sagesharp** [sagesharp/outreachy-django-wagtail#8]
Right now, the menu items are listed in the order that the page was created (which is to say, seemingly random for a normal human). The menu order should be:

* Apply
* Mentor
* Sponsor
* Promote
* Alums
* Opportunities
* Contact

I think it could be fixed here:
https://github.com/sagesharp/outreachy-django-wagtail/blob/f8b0a66c1bf21cac8b53749f404095a9b782265b/outreachyhome/templates/base.html#L48

**Comment by sagesharp** [comment]
On second thought, the navigation bar just is getting to be too unwieldy. There should really be two sub menus: one for people who can benefit from being an Outreachy intern, and another for people who can support the Outreachy program. This probably requires switching to a different bootstrap theme that supports submenus. Related to #12.

Menus should be:
- Participate
  - Apply
  - Alums
  - Opportunities
- Support
  - Volunteer (not sure if we need this one, it's a new category for us based on the on-boarding flows)
  - Mentor
  - Sponsor (goes to corporate sponsorship page)
  - Donate (goes to individual donation page)
  - Promote
- Blog
- Contact

**Comment by danvet** [comment]
Figured this fits here: It took me forever to realize that I can click on the "dashboard" link in the title bar - well I never figured it out, Julia Lawall had to tell me. Since the visual style is entirely different I figured it's the label for the menu bar, not something that actually shows a page. I'm not a UX expert, but making it look/act the same, or maybe pushing it somehow into the account menu as one of two submenus: "Personal Data" and "Dashboard.

2nd item, some easier way to navigate to pages not in the top level menu would be great (more submenus, not sure). Atm I just randomly click around, dread to scroll through the walls of text I've read already (but don't remember exactly where the link is I need), routinely manage to end up on page for interns and get redirected to the elligbility check (at least I've seen that tons of time), then restart and eventually find what I was trying to find. Sometimes also not.

**Comment by sagesharp** [comment]
@danvet I've just pushed a change to the menu bar that hopefully addresses your issue. If there's something confusing (or missing) in the new layout, please comment and re-open this issue.

Fixed in bff1b8e6daa0e80ad1813f0edbb9d14f9bca2b65
